# Generated by Django 4.1.2 on 2022-11-22 13:44

from django.db import migrations, models
import django.db.models.deletion
import store_origin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('tel', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Адрес')),
                ('email', models.CharField(max_length=100, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('vendor_code', models.CharField(default='IRDFHKI8ZR2WRGOMFQPK', max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Артикул')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('short_comment', models.TextField(max_length=100, verbose_name='Краткое описание')),
                ('full_comment', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Полное описание')),
                ('base_price', models.FloatField(verbose_name='Базовая цена')),
                ('current_price', models.FloatField(verbose_name='Текущая цена')),
                ('reserve_amount', models.IntegerField(verbose_name='Запас на складе')),
                ('min_num', models.IntegerField(blank=True, null=True, verbose_name='Минимальное количество')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-vendor_code'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер заказа')),
                ('payment_method', models.CharField(choices=[('Online', 'Онлайн оплата'), ('Card', 'Картой курьеру'), ('Cash', 'Наличными')], max_length=10, verbose_name='Метод оплаты')),
                ('delivery_method', models.CharField(choices=[('Courier', 'Курьером'), ('Self', 'Самовывоз'), ('Post', 'Почта России'), ('CDEK', 'Доставка CDEK')], max_length=10, verbose_name='Метод доставки')),
                ('order_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата заказа')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store_origin.client', verbose_name='Клиент')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store_origin.item', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-order_date'],
            },
        ),
    ]
