# Generated by Django 4.1.2 on 2022-11-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_origin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='vendor_code',
            field=models.CharField(default='YL7NBLYLUD7NR7VRWB6L', max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Артикул'),
        ),
    ]
