# Generated by Django 4.1.2 on 2022-11-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_origin', '0006_alter_item_vendor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_it',
            field=models.AutoField(default=0, primary_key=True, serialize=False, unique=True, verbose_name='ID товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='vendor_code',
            field=models.CharField(default='IU3WNF90GISO9MG1T23Y', max_length=20, unique=True, verbose_name='Артикул'),
        ),
    ]
