# Generated by Django 4.1.2 on 2022-12-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_origin', '0008_alter_item_vendor_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_it',
            new_name='item_id',
        ),
        migrations.AlterField(
            model_name='item',
            name='vendor_code',
            field=models.CharField(default='WRURKQJ2ZXGO87G5CJ4K', max_length=20, unique=True, verbose_name='Артикул'),
        ),
    ]
