# Generated by Django 4.1.2 on 2022-12-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_origin', '0009_rename_item_it_item_item_id_alter_item_vendor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='vendor_code',
            field=models.CharField(default='H1FE48I79EL34TWVYRFM', max_length=20, unique=True, verbose_name='Артикул'),
        ),
    ]
