# Generated by Django 4.1.2 on 2022-12-05 18:16

from django.db import migrations, models
import store_origin.models


class Migration(migrations.Migration):

    dependencies = [
        ('store_origin', '0011_alter_item_vendor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='ID товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='vendor_code',
            field=models.CharField(default=store_origin.models.Item.generate_code, max_length=20, unique=True, verbose_name='Артикул'),
        ),
    ]
