# Generated by Django 4.1.2 on 2022-12-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_origin', '0012_alter_item_item_id_alter_item_vendor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_price',
            field=models.FloatField(default=0.0, verbose_name='Текущая цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID товара'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ManyToManyField(to='store_origin.item', verbose_name='Товар'),
        ),
    ]
