# Generated by Django 4.1.2 on 2022-12-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_origin', '0013_order_current_price_alter_item_item_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='current_price',
        ),
        migrations.AddField(
            model_name='order',
            name='order_price',
            field=models.FloatField(default=0.0, verbose_name='Стоимость заказа'),
            preserve_default=False,
        ),
    ]
