# Generated by Django 4.1.2 on 2022-12-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_origin', '0014_rename_item_order_items_remove_order_current_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('Курьером', 'Курьером'), ('Самовывоз', 'Самовывоз'), ('Почта России', 'Почта России'), ('Доставка CDEK', 'Доставка CDEK')], max_length=20, verbose_name='Метод доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Онлайн оплата', 'Онлайн оплата'), ('Картой курьеру', 'Картой курьеру'), ('Наличными', 'Наличными')], max_length=20, verbose_name='Метод оплаты'),
        ),
    ]
